version: '2'

services:
  app:
    image: 'rekkme-backend:latest'
    build:
      context: .
    ports:
      - 8080:8080
    container_name: app
    depends_on:
      - db
    #environment:
    #  - SPRING_DATASOURCE_URL=jdbc:postgres://vydmuyigwpjxwz:e81e6177e0d6a1f662bed25edd74ca1c8f02e1705671ab531a27b3522c2c7d29@ec2-44-199-52-133.compute-1.amazonaws.com:5432/dcqf1mmo2eddlm?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
    #  - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: rekkme-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres