version: '2'

services:
  app:
    image: 'rekkme-backend:latest'
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - ${PORT}:${PORT}
    container_name: rekkme-backend-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=${PORT}
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: rekkme-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}