INSERT INTO CATEGORIES (NAME) VALUES ('Music');
INSERT INTO CATEGORIES (NAME) VALUES ('Movies and TV');
INSERT INTO CATEGORIES (NAME) VALUES ('Products');
INSERT INTO CATEGORIES (NAME) VALUES ('Restaurants');
INSERT INTO CATEGORIES (NAME) VALUES ('Travel');

INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, LAST_LOGIN, REK_POINTS, KOS) VALUES ('gcpetri', 'Gregory', 'Petri', 'gcpetri@tamu.edu', LOCALTIMESTAMP, 500, 2);
INSERT INTO AUTH (USER_ID, PASSWORD) VALUES (1, 'password');
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, LAST_LOGIN, REK_POINTS, KOS) VALUES ('tatiaris', 'Rish', 'Tatia', 'tatiaris@tamu.edu', LOCALTIMESTAMP, 1000, 12);
INSERT INTO AUTH (USER_ID, PASSWORD) VALUES (2, 'password');
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, LAST_LOGIN, REK_POINTS, KOS) VALUES ('dantheman', 'Dan', 'Abreo', 'dan.abreo@tamu.edu', LOCALTIMESTAMP, 200, 10);
INSERT INTO AUTH (USER_ID, PASSWORD) VALUES (3, 'password');
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, LAST_LOGIN, REK_POINTS, KOS) VALUES ('gcurious', 'Curious', 'George', 'gcurious@tamu.edu', LOCALTIMESTAMP, 900, 0);
INSERT INTO AUTH (USER_ID, PASSWORD) VALUES (4, 'password');
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, LAST_LOGIN, REK_POINTS, KOS) VALUES ('theaggie', 'Maddie', 'The Aggie', 'theaggie@tamu.edu', LOCALTIMESTAMP, 100000, 20);
INSERT INTO AUTH (USER_ID, PASSWORD) VALUES (5, 'password');

INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (1, 2);
INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (1, 3);
INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (2, 1);
INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (2, 4);
INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (3, 4);
INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (3, 1);
INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (3, 2);

INSERT INTO REKS (TO_USER_ID, FROM_USER_ID, CONTENT, CATEGORY_ID, WAGER, URL, CREATED_ON) VALUES (2, 1, 'Check this song out!', 1, 200, 'https://open.spotify.com/track/2DkZisoN9h1dLa8Sn5sx0n?si=203a3183a3554086', LOCALTIMESTAMP);
INSERT INTO REKS (TO_USER_ID, FROM_USER_ID, CONTENT, CATEGORY_ID, WAGER, URL, CREATED_ON) VALUES (1, 3, 'This show bro...', 2, 100, 'https://www.warnerbros.com/movies/lord-rings-fellowship-ring', LOCALTIMESTAMP); 
INSERT INTO REKS (TO_USER_ID, FROM_USER_ID, CONTENT, CATEGORY_ID, WAGER, URL, CREATED_ON) VALUES (1, 4, 'I LOVE THIS RESTAURANT', 4, 800, 'https://torchystacos.com/', LOCALTIMESTAMP);  

